export const DarkMode =() =>{

    let $DarkModeIcon = document.querySelector("#button-icon-dark-mode")   
    let $DarkModeButton = document.querySelector("#button-dark-mode")
    let $body = document.querySelector("#body")
    let $gradient = document.querySelector("#gradient")
    let $we = document.querySelector("#we")
    let $cut = document.querySelector("#cut")
    let $security = document.querySelector("#security")
    let $barber = document.querySelector("#barber")
    let $footer = document.querySelector("#footer")
    let $footerLinkFacebook = document.querySelector("#footer-social-media-menu-link-facebook")
    let $footerLinkInstagram = document.querySelector("#footer-social-media-menu-link-instagram")
    let $path = document.querySelector("#path")
    let $entertainmetn = document.querySelector("#we-entertainment-image")
    let $relaxed = document.querySelector("#we-relaxed-image")
    let $gallery = document.querySelector("#we-gallery-image")
    let $menu = document.querySelector("#menu")
    let $iconX = document.querySelector("#menu-icon-x")
    let $itemHome = document.querySelector("#menu-link-home")
    let $temPrice = document.querySelector("#menu-link-price")
    let $itemProduct = document.querySelector("#menu-link-product")
    
    document.addEventListener("click",(e)=>{

        if (e.target.matches(".button__dark__mode") || e.target.matches(".button__icon__dark__mode")) {
            $body.classList.toggle("body__dark")
            $gradient.classList.toggle("gradient__dark")
            $we.classList.toggle("we__dark")
            $cut.classList.toggle("cut__dark")
            $security.classList.toggle("security__dark")
            $barber.classList.toggle("barber__dark")
            $footer.classList.toggle("footer__dark")
            $footerLinkFacebook.classList.toggle("footer__social-media__menu__link__dark")
            $footerLinkInstagram.classList.toggle("footer__social-media__menu__link__dark")
            $path.classList.toggle("path__dark")
            $menu.classList.toggle("menu__dark")
            $iconX.classList.toggle("menu__icon__x__dark")
            $itemHome.classList.toggle("menu__link__dark")
            $temPrice.classList.toggle("menu__link__dark")
            $itemProduct.classList.toggle("menu__link__dark")
            $DarkModeButton.classList.toggle("button__dark__mode__dark")
            
            if ($body.classList.contains("body__dark")) {
                localStorage.setItem("dark-mode","true")
            } else {
                localStorage.setItem("dark-mode","false")
            }
        }

        if ($body.classList.contains("body__dark")) {
            $DarkModeIcon.classList.add("fa-moon")
            $DarkModeIcon.classList.remove("fa-sun")
            $DarkModeIcon.classList.add("button__dark__mode__icon__dark")
            $DarkModeIcon.classList.remove("button__dark__mode__icon")
            
            $entertainmetn.setAttribute("src","recursos/images/video-dark.svg")
            $relaxed.setAttribute("src","recursos/images/relaxin-dark.svg")
            $gallery.setAttribute("src","recursos/images/galery-dark.svg")
        }else{
            $DarkModeIcon.classList.add("fa-sun")
            $DarkModeIcon.classList.remove("fa-moon")
            $entertainmetn.setAttribute("src","recursos/images/video-light.svg")
            $relaxed.setAttribute("src","recursos/images/relaxin-light.svg")
            $gallery.setAttribute("src","recursos/images/galery-ligh.svg")
            $DarkModeIcon.classList.remove("button__dark__mode__icon__dark")
            $DarkModeIcon.classList.add("button__dark__mode__icon")
        }
    })

    if (localStorage.getItem("dark-mode") === `true`) {
            $body.classList.add("body__dark")
            $gradient.classList.add("gradient__dark")
            $we.classList.add("we__dark")
            $cut.classList.add("cut__dark")
            $security.classList.add("security__dark")
            $barber.classList.add("barber__dark")
            $footer.classList.add("footer__dark")
            $footerLinkFacebook.classList.add("footer__social-media__menu__link__dark")
            $footerLinkInstagram.classList.add("footer__social-media__menu__link__dark")
            $path.classList.add("path__dark")
            $menu.classList.add("menu__dark")
            $iconX.classList.add("menu__icon__x__dark")
            $itemHome.classList.add("menu__link__dark")
            $temPrice.classList.add("menu__link__dark")
            $itemProduct.classList.add("menu__link__dark")
            $DarkModeButton.classList.add("button__dark__mode__dark")
            $DarkModeIcon.classList.add("fa-moon")
            $DarkModeIcon.classList.remove("fa-sun")
            $DarkModeIcon.classList.add("button__dark__mode__icon__dark")
            $DarkModeIcon.classList.remove("button__dark__mode__icon")
            
            $entertainmetn.setAttribute("src","recursos/images/video-dark.svg")
            $relaxed.setAttribute("src","recursos/images/relaxin-dark.svg")
            $gallery.setAttribute("src","recursos/images/galery-dark.svg")
    } else {
        $body.classList.remove("body__dark")
            $gradient.classList.remove("gradient__dark")
            $we.classList.remove("we__dark")
            $cut.classList.remove("cut__dark")
            $security.classList.remove("security__dark")
            $barber.classList.remove("barber__dark")
            $footer.classList.remove("footer__dark")
            $footerLinkFacebook.classList.remove("footer__social-media__menu__link__dark")
            $footerLinkInstagram.classList.remove("footer__social-media__menu__link__dark")
            $path.classList.remove("path__dark")
            $menu.classList.remove("menu__dark")
            $iconX.classList.remove("menu__icon__x__dark")
            $itemHome.classList.remove("menu__link__dark")
            $temPrice.classList.remove("menu__link__dark")
            $itemProduct.classList.remove("menu__link__dark")
            $DarkModeButton.classList.remove("button__dark__mode__dark")
            $DarkModeIcon.classList.add("fa-sun")
            $DarkModeIcon.classList.remove("fa-moon")
            $entertainmetn.setAttribute("src","recursos/images/video-light.svg")
            $relaxed.setAttribute("src","recursos/images/relaxin-light.svg")
            $gallery.setAttribute("src","recursos/images/galery-ligh.svg")
            $DarkModeIcon.classList.remove("button__dark__mode__icon__dark")
            $DarkModeIcon.classList.add("button__dark__mode__icon")
    }
}